# Project-wide Gradle settings

# Gradle JVM
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Djna.nosys=true

# AndroidX / Kotlin
android.useAndroidX=true
kotlin.code.style=official

# Leaner R classes
android.nonTransitiveRClass=true

# 16KB page-size / performance toggles
android.experimental.enableArtProfiles=true
android.experimental.r8.dex-startup-optimization=true
android.experimental.enableScreenshotTest=false
android.enableR8.fullMode=true
org.gradle.configuration-cache=true

# --- Optional build speedups ---
# org.gradle.parallel=true
# org.gradle.caching=true
# org.gradle.configuration-cache=true
